# Envoy takes several hours to build. We use disk cache to allow rebuilds when needed
# to finish much faster, however GitHub actions does not allow the cache created in a PR
# build to be used in the main branch build. To avoid multiple multi-hour builds, we only
# run Windows CI on the main branch.
name: CI (Windows)
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  # Cancel in-progress jobs for PRs only
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6

      - run: uv lock --check

      - run: uv sync

      - id: envoy-version
        shell: bash
        run: echo "version=$(uv run poe print-envoy-version)" >> $GITHUB_OUTPUT

      - uses: ./.github/actions/build-windows
        with:
          version: ${{ steps.envoy-version.outputs.version }}

      - name: run tests
        run: uv run poe test -s

      - run: uv run poe build
