name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  attestations: write
  id-token: write

concurrency:
  # Cancel in-progress jobs for PRs only
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15
          - ubuntu-24.04
          - windows-2025
    runs-on: ${{ matrix.os }}
    environment: ${{ github.event_name != 'pull_request' && 'dev' || null }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      # By default, docker would try to use Windows containers but we want to use
      # Linux, which will match any conceivable setup for developers using docker
      - uses: ./.github/actions/setup-wsl
        if: startsWith(matrix.os, 'windows-')

      - uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3 # v7.1.3

      - run: uv lock --check

      - run: uv sync

      - run: uv run poe check
        continue-on-error: true

      - if: startsWith(matrix.os, 'windows-')
        run: |
          docker ps
          wsl ls -al /mnt/c/Users/runneradmin/AppData/Local/Temp

      - run: uv run poe wheels
        if: startsWith(matrix.os, 'ubuntu-')

      - uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        if: github.event_name != 'pull_request' && startsWith(matrix.os, 'ubuntu-')
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
