name: Build upstream Envoy on Windows
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  # Cancel in-progress jobs for PRs only
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: ./.github/actions/build-windows
        with:
          version: fix-windows-build
          repository: anuraaga/envoy
          patch: .github/actions/build-windows/v1.37.patch

      - uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
        with:
          cache-dependency-glob: "**/uv.lock"

      - run: uv lock --check

      - run: uv sync

      - name: run tests
        run: uv run poe test

      - run: uv run poe build
