name: Build upstream Envoy on Windows
on:
  schedule:
    - cron: "5 4 * * *"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  # Cancel in-progress jobs for PRs only
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/build-windows
        with:
          version: main
          repository: envoyproxy/envoy
          patch: .github/actions/build-windows/main.patch

      - uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0
        with:
          cache-dependency-glob: "**/uv.lock"

      - run: uv lock --check

      - run: uv sync

      - name: run tests
        run: uv run poe test

      - run: uv run poe build
