name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  id-token: write
  attestations: write

jobs:
  build-unix:
    runs-on: ubuntu-24.04
    environment: ${{ github.event_name == 'push' && 'prod' || 'dev' }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0

      - name: Build wheels
        run: uv run poe unix-wheels

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: unix-wheels
          path: dist/

  build-windows:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0

      - id: envoy-version
        shell: bash
        run: echo "version=$(uv run poe print-envoy-version)" >> $GITHUB_OUTPUT

      - uses: ./.github/actions/build-windows
        with:
          version: ${{ steps.envoy-version.outputs.version }}
          patch: github/actions/build-windows/v1.37.patch

      - name: Build wheel
        run: uv run poe build

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: windows-wheels
          path: dist/

  publish:
    needs:
      - build-unix
      - build-windows
    runs-on: ubuntu-24.04
    environment: ${{ github.event_name == 'push' && 'prod' || 'dev' }}
    steps:
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          path: dist/
          merge-multiple: true

      # Only supports unix runner
      - uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          repository-url: ${{ github.event_name != 'push' && 'https://test.pypi.org/legacy/' || null }}
          skip-existing: ${{ github.event_name != 'push' }}
