name: Windows
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  attestations: write
  id-token: write

concurrency:
  # Cancel in-progress jobs for PRs only
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-2025
    environment: ${{ github.event_name != 'pull_request' && 'dev' || null }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: envoyproxy/envoy
          ref: v1.36.3
          path: out/envoy-build

      - name: build envoy
        working-directory: out/envoy-build
        shell: pwsh
        run: |
          # Find the latest Visual Studio installation with C++ tools
          $vsPath = (vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath | Select-Object -First 1)

          # Construct the path to the DevShell module and import it
          Import-Module (Join-Path $vsPath "Common7\Tools\Microsoft.VisualStudio.DevShell.dll")

          # Enter the VS Developer Shell environment
          Enter-VsDevShell -VsInstallPath $vsPath -SkipAutomaticLocation -DevCmdArguments "-arch=amd64"

          # Run the build
          bazel build -c opt `
            --config=clang-cl `
            --cxxopt=/std:c++20 `
            --host_cxxopt=/std:c++20 `
            --copt=-Wno-error=implicit-function-declaration `
            --copt=-Wno-error=unknown-argument `
            --cxxopt=/FIstring `
            --repo_env=PATH `
            --verbose_failures `
            --curses=no `
            --noincompatible_strict_action_env `
            envoy
