name: Windows
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  attestations: write
  id-token: write

concurrency:
  # Cancel in-progress jobs for PRs only
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-2025
    environment: ${{ github.event_name != 'pull_request' && 'dev' || null }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: envoyproxy/envoy
          ref: v1.36.3
          path: out/envoy-build

      - uses: bazel-contrib/setup-bazel@4fd964a13a440a8aeb0be47350db2fc640f19ca8 # 0.15.0
        with:
          disk-cache: v1.36.3-0
          repository-cache: true

      - name: Apply patches
        shell: bash
        run: |
          cp envoy_windows_fixes.patch out/envoy-build/
          cd out/envoy-build
          git apply envoy_windows_fixes.patch

      - name: build envoy
        working-directory: out/envoy-build
        shell: pwsh
        run: |
          New-Item -Path "C:\Program Files\LLVM\bin\link.exe" -ItemType SymbolicLink -Value "C:\Program Files\LLVM\bin\lld-link.exe"

          # Run the build
          bazel build --keep_going -c opt `
            --config=clang-cl `
            --cxxopt=/std:c++20 `
            --host_cxxopt=/std:c++20 `
            --copt=-Wno-error=implicit-function-declaration `
            --copt=-Wno-error=unknown-argument `
            --copt=-Wno-nullability-completeness `
            --cxxopt=/FIstring `
            --per_file_copt=source/extensions/http/ext_proc/.*@-Wno-nontrivial-memcall `
            --per_file_copt=source/extensions/filters/common/expr/.*@-Wno-nontrivial-memcall `
            --per_file_copt=source/extensions/filters/http/ext_proc/.*@-Wno-nontrivial-memcall `
            --per_file_copt=source/extensions/tracers/opentelemetry/samplers/cel/.*@-Wno-nontrivial-memcall `
            --per_file_copt=external/com_google_cel_cpp/.*@/DWIN32_LEAN_AND_MEAN `
            --per_file_copt=external/com_google_cel_cpp/.*@/DNOUSER `
            --per_file_copt=external/com_google_cel_cpp/.*@/DNOGDI `
            --repo_env=PATH `
            --verbose_failures `
            --curses=no `
            --noincompatible_strict_action_env `
            envoy
